# Physical parameters for mecanum base
/kinematics_engine_node:
  ros__parameters:
    half_length: 0.12
    half_width: 0.10
    wheel_radius: 0.05
    topic_cmd_vel: "cmd_vel"
    topic_wheel_speeds: "wheel_speeds"
