name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ros_build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy, humble]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            at_motor_driver
            base_teleop
            mecanum_kinematics
            robot_bringup
            robot_interfaces
          target-ros2-distro: ${{ matrix.ros_distro }}
          source-ros2-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: ""
          # Path to the workspace source
          colcon-defaults: |
            {
              "build": {
                "base-paths": ["lazytatzv_ws"]
              },
              "test": {
                "base-paths": ["lazytatzv_ws"]
              }
            }
          # Use the cache to speed up subsequent builds
          colcon-mixin-name: release
          import-token: ${{ secrets.GITHUB_TOKEN }}
